# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/ActivitySponsor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/ActivitySponsor.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1etbclient/ActivitySponsor.proto\x12\x08tbclient\":\n\x0f\x41\x63tivitySponsor\x12\x12\n\nis_sponsor\x18\x01 \x01(\x05\x12\x13\n\x0bsponsor_url\x18\x02 \x01(\t')
)




_ACTIVITYSPONSOR = _descriptor.Descriptor(
  name='ActivitySponsor',
  full_name='tbclient.ActivitySponsor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_sponsor', full_name='tbclient.ActivitySponsor.is_sponsor', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sponsor_url', full_name='tbclient.ActivitySponsor.sponsor_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['ActivitySponsor'] = _ACTIVITYSPONSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActivitySponsor = _reflection.GeneratedProtocolMessageType('ActivitySponsor', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVITYSPONSOR,
  __module__ = 'tbclient.ActivitySponsor_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ActivitySponsor)
  ))
_sym_db.RegisterMessage(ActivitySponsor)


# @@protoc_insertion_point(module_scope)
