# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/AlbumInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/AlbumInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x18tbclient/AlbumInfo.proto\x12\x08tbclient\"\x9c\x02\n\tAlbumInfo\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\x04\x12\x12\n\nalbum_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\r\x12\x10\n\x08\x65nd_time\x18\x06 \x01(\r\x12\x13\n\x0bhas_collect\x18\x0f \x01(\x08\x12\x0c\n\x04latd\x18\x0c \x01(\x01\x12\x10\n\x08location\x18\n \x01(\t\x12\x0e\n\x06longtd\x18\x0b \x01(\x01\x12\x10\n\x08num_high\x18\t \x01(\r\x12\x10\n\x08num_join\x18\x08 \x01(\r\x12\x10\n\x08portrait\x18\x0e \x01(\t\x12\x12\n\nstart_time\x18\x05 \x01(\r\x12\x0b\n\x03uid\x18\x03 \x01(\x04\x12\x13\n\x0bupdate_time\x18\x07 \x01(\r\x12\x11\n\tuser_name\x18\r \x01(\t')
)




_ALBUMINFO = _descriptor.Descriptor(
  name='AlbumInfo',
  full_name='tbclient.AlbumInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='album_id', full_name='tbclient.AlbumInfo.album_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='album_name', full_name='tbclient.AlbumInfo.album_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='tbclient.AlbumInfo.create_time', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='tbclient.AlbumInfo.end_time', index=3,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_collect', full_name='tbclient.AlbumInfo.has_collect', index=4,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latd', full_name='tbclient.AlbumInfo.latd', index=5,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='tbclient.AlbumInfo.location', index=6,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longtd', full_name='tbclient.AlbumInfo.longtd', index=7,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_high', full_name='tbclient.AlbumInfo.num_high', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_join', full_name='tbclient.AlbumInfo.num_join', index=9,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portrait', full_name='tbclient.AlbumInfo.portrait', index=10,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='tbclient.AlbumInfo.start_time', index=11,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='tbclient.AlbumInfo.uid', index=12,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='tbclient.AlbumInfo.update_time', index=13,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='tbclient.AlbumInfo.user_name', index=14,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['AlbumInfo'] = _ALBUMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlbumInfo = _reflection.GeneratedProtocolMessageType('AlbumInfo', (_message.Message,), dict(
  DESCRIPTOR = _ALBUMINFO,
  __module__ = 'tbclient.AlbumInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.AlbumInfo)
  ))
_sym_db.RegisterMessage(AlbumInfo)


# @@protoc_insertion_point(module_scope)
