# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/AndroidBfbSdk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/AndroidBfbSdk.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/AndroidBfbSdk.proto\x12\x08tbclient\"\x8d\x01\n\rAndroidBfbSdk\x12\x13\n\x0b\x61\x63tivity_no\x18\x03 \x01(\t\x12\x10\n\x08order_no\x18\x04 \x01(\t\x12\x12\n\nreturn_url\x18\x05 \x01(\t\x12\x0c\n\x04sign\x18\x06 \x01(\t\x12\x13\n\x0bsign_method\x18\x07 \x01(\x05\x12\r\n\x05sp_no\x18\x01 \x01(\x05\x12\x0f\n\x07version\x18\x02 \x01(\t')
)




_ANDROIDBFBSDK = _descriptor.Descriptor(
  name='AndroidBfbSdk',
  full_name='tbclient.AndroidBfbSdk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activity_no', full_name='tbclient.AndroidBfbSdk.activity_no', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_no', full_name='tbclient.AndroidBfbSdk.order_no', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_url', full_name='tbclient.AndroidBfbSdk.return_url', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign', full_name='tbclient.AndroidBfbSdk.sign', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign_method', full_name='tbclient.AndroidBfbSdk.sign_method', index=4,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sp_no', full_name='tbclient.AndroidBfbSdk.sp_no', index=5,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='tbclient.AndroidBfbSdk.version', index=6,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['AndroidBfbSdk'] = _ANDROIDBFBSDK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AndroidBfbSdk = _reflection.GeneratedProtocolMessageType('AndroidBfbSdk', (_message.Message,), dict(
  DESCRIPTOR = _ANDROIDBFBSDK,
  __module__ = 'tbclient.AndroidBfbSdk_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.AndroidBfbSdk)
  ))
_sym_db.RegisterMessage(AndroidBfbSdk)


# @@protoc_insertion_point(module_scope)
