# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/AnimationThread.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/AnimationThread.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1etbclient/AnimationThread.proto\x12\x08tbclient\"6\n\x0f\x41nimationThread\x12\x10\n\x08jump_url\x18\x02 \x01(\t\x12\x11\n\tvideo_pic\x18\x01 \x01(\t')
)




_ANIMATIONTHREAD = _descriptor.Descriptor(
  name='AnimationThread',
  full_name='tbclient.AnimationThread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jump_url', full_name='tbclient.AnimationThread.jump_url', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_pic', full_name='tbclient.AnimationThread.video_pic', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['AnimationThread'] = _ANIMATIONTHREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnimationThread = _reflection.GeneratedProtocolMessageType('AnimationThread', (_message.Message,), dict(
  DESCRIPTOR = _ANIMATIONTHREAD,
  __module__ = 'tbclient.AnimationThread_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.AnimationThread)
  ))
_sym_db.RegisterMessage(AnimationThread)


# @@protoc_insertion_point(module_scope)
