# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/AppCode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/AppCode.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x16tbclient/AppCode.proto\x12\x08tbclient\"C\n\x07\x41ppCode\x12\x13\n\x0b\x62utton_text\x18\x03 \x01(\t\x12\x11\n\tgame_icon\x18\x01 \x01(\t\x12\x10\n\x08post_url\x18\x02 \x01(\t')
)




_APPCODE = _descriptor.Descriptor(
  name='AppCode',
  full_name='tbclient.AppCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button_text', full_name='tbclient.AppCode.button_text', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_icon', full_name='tbclient.AppCode.game_icon', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_url', full_name='tbclient.AppCode.post_url', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['AppCode'] = _APPCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppCode = _reflection.GeneratedProtocolMessageType('AppCode', (_message.Message,), dict(
  DESCRIPTOR = _APPCODE,
  __module__ = 'tbclient.AppCode_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.AppCode)
  ))
_sym_db.RegisterMessage(AppCode)


# @@protoc_insertion_point(module_scope)
