# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/AppInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/AppInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x16tbclient/AppInfo.proto\x12\x08tbclient\"i\n\x07\x41ppInfo\x12\x1b\n\x13\x61\x64_apk_package_name\x18\x04 \x01(\t\x12\r\n\x05\x61\x64_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61pk_url\x18\x03 \x01(\t\x12\x10\n\x08\x61pp_size\x18\x05 \x01(\x03')
)




_APPINFO = _descriptor.Descriptor(
  name='AppInfo',
  full_name='tbclient.AppInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_apk_package_name', full_name='tbclient.AppInfo.ad_apk_package_name', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad_id', full_name='tbclient.AppInfo.ad_id', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad_name', full_name='tbclient.AppInfo.ad_name', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apk_url', full_name='tbclient.AppInfo.apk_url', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_size', full_name='tbclient.AppInfo.app_size', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['AppInfo'] = _APPINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppInfo = _reflection.GeneratedProtocolMessageType('AppInfo', (_message.Message,), dict(
  DESCRIPTOR = _APPINFO,
  __module__ = 'tbclient.AppInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.AppInfo)
  ))
_sym_db.RegisterMessage(AppInfo)


# @@protoc_insertion_point(module_scope)
