# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/Balv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/Balv.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x13tbclient/Balv.proto\x12\x08tbclient\"?\n\x04\x42\x61lv\x12\x13\n\x0b\x64\x61ys_tofree\x18\x03 \x01(\x05\x12\x10\n\x08is_black\x18\x01 \x01(\x05\x12\x10\n\x08is_block\x18\x02 \x01(\x05')
)




_BALV = _descriptor.Descriptor(
  name='Balv',
  full_name='tbclient.Balv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='days_tofree', full_name='tbclient.Balv.days_tofree', index=0,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_black', full_name='tbclient.Balv.is_black', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_block', full_name='tbclient.Balv.is_block', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['Balv'] = _BALV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Balv = _reflection.GeneratedProtocolMessageType('Balv', (_message.Message,), dict(
  DESCRIPTOR = _BALV,
  __module__ = 'tbclient.Balv_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.Balv)
  ))
_sym_db.RegisterMessage(Balv)


# @@protoc_insertion_point(module_scope)
