# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/BannerFollowLive.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import AlaLiveInfo_pb2 as tbclient_dot_AlaLiveInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/BannerFollowLive.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/BannerFollowLive.proto\x12\x08tbclient\x1a\x1atbclient/AlaLiveInfo.proto\"Q\n\x10\x42\x61nnerFollowLive\x12\x0f\n\x07_switch\x18\x02 \x01(\r\x12,\n\rala_live_list\x18\x01 \x03(\x0b\x32\x15.tbclient.AlaLiveInfo')
  ,
  dependencies=[tbclient_dot_AlaLiveInfo__pb2.DESCRIPTOR,])




_BANNERFOLLOWLIVE = _descriptor.Descriptor(
  name='BannerFollowLive',
  full_name='tbclient.BannerFollowLive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_switch', full_name='tbclient.BannerFollowLive._switch', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ala_live_list', full_name='tbclient.BannerFollowLive.ala_live_list', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=154,
)

_BANNERFOLLOWLIVE.fields_by_name['ala_live_list'].message_type = tbclient_dot_AlaLiveInfo__pb2._ALALIVEINFO
DESCRIPTOR.message_types_by_name['BannerFollowLive'] = _BANNERFOLLOWLIVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BannerFollowLive = _reflection.GeneratedProtocolMessageType('BannerFollowLive', (_message.Message,), dict(
  DESCRIPTOR = _BANNERFOLLOWLIVE,
  __module__ = 'tbclient.BannerFollowLive_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.BannerFollowLive)
  ))
_sym_db.RegisterMessage(BannerFollowLive)


# @@protoc_insertion_point(module_scope)
