# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/BookThread.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/BookThread.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x19tbclient/BookThread.proto\x12\x08tbclient\"D\n\nBookThread\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\x11\n\tbook_type\x18\x02 \x01(\r\x12\x12\n\nchapter_id\x18\x03 \x01(\x04')
)




_BOOKTHREAD = _descriptor.Descriptor(
  name='BookThread',
  full_name='tbclient.BookThread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_id', full_name='tbclient.BookThread.book_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='book_type', full_name='tbclient.BookThread.book_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chapter_id', full_name='tbclient.BookThread.chapter_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['BookThread'] = _BOOKTHREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookThread = _reflection.GeneratedProtocolMessageType('BookThread', (_message.Message,), dict(
  DESCRIPTOR = _BOOKTHREAD,
  __module__ = 'tbclient.BookThread_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.BookThread)
  ))
_sym_db.RegisterMessage(BookThread)


# @@protoc_insertion_point(module_scope)
