# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/CartoonChapterInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/CartoonChapterInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n!tbclient/CartoonChapterInfo.proto\x12\x08tbclient\"=\n\x12\x43\x61rtoonChapterInfo\x12\x12\n\nchapter_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63hapter_vip\x18\x02 \x01(\r')
)




_CARTOONCHAPTERINFO = _descriptor.Descriptor(
  name='CartoonChapterInfo',
  full_name='tbclient.CartoonChapterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chapter_id', full_name='tbclient.CartoonChapterInfo.chapter_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chapter_vip', full_name='tbclient.CartoonChapterInfo.chapter_vip', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['CartoonChapterInfo'] = _CARTOONCHAPTERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CartoonChapterInfo = _reflection.GeneratedProtocolMessageType('CartoonChapterInfo', (_message.Message,), dict(
  DESCRIPTOR = _CARTOONCHAPTERINFO,
  __module__ = 'tbclient.CartoonChapterInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.CartoonChapterInfo)
  ))
_sym_db.RegisterMessage(CartoonChapterInfo)


# @@protoc_insertion_point(module_scope)
