# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/CartoonThread.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/CartoonThread.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/CartoonThread.proto\x12\x08tbclient\"7\n\rCartoonThread\x12\x12\n\ncartoon_id\x18\x01 \x01(\x03\x12\x12\n\nchapter_id\x18\x02 \x01(\x05')
)




_CARTOONTHREAD = _descriptor.Descriptor(
  name='CartoonThread',
  full_name='tbclient.CartoonThread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cartoon_id', full_name='tbclient.CartoonThread.cartoon_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chapter_id', full_name='tbclient.CartoonThread.chapter_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['CartoonThread'] = _CARTOONTHREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CartoonThread = _reflection.GeneratedProtocolMessageType('CartoonThread', (_message.Message,), dict(
  DESCRIPTOR = _CARTOONTHREAD,
  __module__ = 'tbclient.CartoonThread_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.CartoonThread)
  ))
_sym_db.RegisterMessage(CartoonThread)


# @@protoc_insertion_point(module_scope)
