# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/CategoryInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/CategoryInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1btbclient/CategoryInfo.proto\x12\x08tbclient\":\n\x0c\x43\x61tegoryInfo\x12\x13\n\x0b\x63\x61tegory_id\x18\x01 \x01(\x05\x12\x15\n\rcategory_name\x18\x02 \x01(\t')
)




_CATEGORYINFO = _descriptor.Descriptor(
  name='CategoryInfo',
  full_name='tbclient.CategoryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category_id', full_name='tbclient.CategoryInfo.category_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category_name', full_name='tbclient.CategoryInfo.category_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['CategoryInfo'] = _CATEGORYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CategoryInfo = _reflection.GeneratedProtocolMessageType('CategoryInfo', (_message.Message,), dict(
  DESCRIPTOR = _CATEGORYINFO,
  __module__ = 'tbclient.CategoryInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.CategoryInfo)
  ))
_sym_db.RegisterMessage(CategoryInfo)


# @@protoc_insertion_point(module_scope)
