# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/DealMedia.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/DealMedia.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x18tbclient/DealMedia.proto\x12\x08tbclient\"P\n\tDealMedia\x12\x0f\n\x07\x62ig_pic\x18\x03 \x01(\t\x12\x11\n\tsmall_pic\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x11\n\twater_pic\x18\x04 \x01(\t')
)




_DEALMEDIA = _descriptor.Descriptor(
  name='DealMedia',
  full_name='tbclient.DealMedia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='big_pic', full_name='tbclient.DealMedia.big_pic', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='small_pic', full_name='tbclient.DealMedia.small_pic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='tbclient.DealMedia.type', index=2,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='water_pic', full_name='tbclient.DealMedia.water_pic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['DealMedia'] = _DEALMEDIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DealMedia = _reflection.GeneratedProtocolMessageType('DealMedia', (_message.Message,), dict(
  DESCRIPTOR = _DEALMEDIA,
  __module__ = 'tbclient.DealMedia_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.DealMedia)
  ))
_sym_db.RegisterMessage(DealMedia)


# @@protoc_insertion_point(module_scope)
