# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/DislikeInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/DislikeInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1atbclient/DislikeInfo.proto\x12\x08tbclient\"9\n\x0b\x44islikeInfo\x12\x12\n\ndislike_id\x18\x02 \x01(\r\x12\x16\n\x0e\x64islike_reason\x18\x01 \x01(\t')
)




_DISLIKEINFO = _descriptor.Descriptor(
  name='DislikeInfo',
  full_name='tbclient.DislikeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dislike_id', full_name='tbclient.DislikeInfo.dislike_id', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dislike_reason', full_name='tbclient.DislikeInfo.dislike_reason', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['DislikeInfo'] = _DISLIKEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DislikeInfo = _reflection.GeneratedProtocolMessageType('DislikeInfo', (_message.Message,), dict(
  DESCRIPTOR = _DISLIKEINFO,
  __module__ = 'tbclient.DislikeInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.DislikeInfo)
  ))
_sym_db.RegisterMessage(DislikeInfo)


# @@protoc_insertion_point(module_scope)
