# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/ForumPresentInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import UserRankPresentInfo_pb2 as tbclient_dot_UserRankPresentInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/ForumPresentInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/ForumPresentInfo.proto\x12\x08tbclient\x1a\"tbclient/UserRankPresentInfo.proto\"U\n\x10\x46orumPresentInfo\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x30\n\tuser_list\x18\x01 \x03(\x0b\x32\x1d.tbclient.UserRankPresentInfo')
  ,
  dependencies=[tbclient_dot_UserRankPresentInfo__pb2.DESCRIPTOR,])




_FORUMPRESENTINFO = _descriptor.Descriptor(
  name='ForumPresentInfo',
  full_name='tbclient.ForumPresentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='tbclient.ForumPresentInfo.content', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_list', full_name='tbclient.ForumPresentInfo.user_list', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=166,
)

_FORUMPRESENTINFO.fields_by_name['user_list'].message_type = tbclient_dot_UserRankPresentInfo__pb2._USERRANKPRESENTINFO
DESCRIPTOR.message_types_by_name['ForumPresentInfo'] = _FORUMPRESENTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForumPresentInfo = _reflection.GeneratedProtocolMessageType('ForumPresentInfo', (_message.Message,), dict(
  DESCRIPTOR = _FORUMPRESENTINFO,
  __module__ = 'tbclient.ForumPresentInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ForumPresentInfo)
  ))
_sym_db.RegisterMessage(ForumPresentInfo)


# @@protoc_insertion_point(module_scope)
