# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsVideo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import ActBtn_pb2 as tbclient_dot_ActBtn__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsVideo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x17tbclient/FrsVideo.proto\x12\x08tbclient\x1a\x15tbclient/ActBtn.proto\"/\n\x08\x46rsVideo\x12#\n\tvideo_act\x18\x01 \x01(\x0b\x32\x10.tbclient.ActBtn')
  ,
  dependencies=[tbclient_dot_ActBtn__pb2.DESCRIPTOR,])




_FRSVIDEO = _descriptor.Descriptor(
  name='FrsVideo',
  full_name='tbclient.FrsVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_act', full_name='tbclient.FrsVideo.video_act', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=107,
)

_FRSVIDEO.fields_by_name['video_act'].message_type = tbclient_dot_ActBtn__pb2._ACTBTN
DESCRIPTOR.message_types_by_name['FrsVideo'] = _FRSVIDEO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrsVideo = _reflection.GeneratedProtocolMessageType('FrsVideo', (_message.Message,), dict(
  DESCRIPTOR = _FRSVIDEO,
  __module__ = 'tbclient.FrsVideo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsVideo)
  ))
_sym_db.RegisterMessage(FrsVideo)


# @@protoc_insertion_point(module_scope)
