# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/GraffitiRankItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/GraffitiRankItem.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/GraffitiRankItem.proto\x12\x08tbclient\"\x91\x01\n\x10GraffitiRankItem\x12\x0e\n\x06g_type\x18\x07 \x01(\x05\x12\x0b\n\x03gid\x18\x01 \x01(\x03\x12\x0f\n\x07is_vote\x18\x04 \x01(\x05\x12\x0e\n\x06pic_id\x18\x06 \x01(\t\x12\x11\n\tthumb_url\x18\x08 \x01(\t\x12\x0b\n\x03uid\x18\x05 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\nvote_count\x18\x03 \x01(\x03')
)




_GRAFFITIRANKITEM = _descriptor.Descriptor(
  name='GraffitiRankItem',
  full_name='tbclient.GraffitiRankItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='g_type', full_name='tbclient.GraffitiRankItem.g_type', index=0,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gid', full_name='tbclient.GraffitiRankItem.gid', index=1,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_vote', full_name='tbclient.GraffitiRankItem.is_vote', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pic_id', full_name='tbclient.GraffitiRankItem.pic_id', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thumb_url', full_name='tbclient.GraffitiRankItem.thumb_url', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='tbclient.GraffitiRankItem.uid', index=5,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='tbclient.GraffitiRankItem.url', index=6,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote_count', full_name='tbclient.GraffitiRankItem.vote_count', index=7,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['GraffitiRankItem'] = _GRAFFITIRANKITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraffitiRankItem = _reflection.GeneratedProtocolMessageType('GraffitiRankItem', (_message.Message,), dict(
  DESCRIPTOR = _GRAFFITIRANKITEM,
  __module__ = 'tbclient.GraffitiRankItem_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.GraffitiRankItem)
  ))
_sym_db.RegisterMessage(GraffitiRankItem)


# @@protoc_insertion_point(module_scope)
