# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/HotThreadInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/HotThreadInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/HotThreadInfo.proto\x12\x08tbclient\"x\n\rHotThreadInfo\x12\x0b\n\x03\x63id\x18\x03 \x01(\r\x12\x0e\n\x06hmtype\x18\x04 \x01(\r\x12\x12\n\nhot_weight\x18\x06 \x01(\x05\x12\x10\n\x08post_num\x18\x02 \x01(\x04\x12\x11\n\tthread_id\x18\x01 \x01(\x04\x12\x11\n\ttime_type\x18\x05 \x01(\r')
)




_HOTTHREADINFO = _descriptor.Descriptor(
  name='HotThreadInfo',
  full_name='tbclient.HotThreadInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='tbclient.HotThreadInfo.cid', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hmtype', full_name='tbclient.HotThreadInfo.hmtype', index=1,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hot_weight', full_name='tbclient.HotThreadInfo.hot_weight', index=2,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_num', full_name='tbclient.HotThreadInfo.post_num', index=3,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='tbclient.HotThreadInfo.thread_id', index=4,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_type', full_name='tbclient.HotThreadInfo.time_type', index=5,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['HotThreadInfo'] = _HOTTHREADINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HotThreadInfo = _reflection.GeneratedProtocolMessageType('HotThreadInfo', (_message.Message,), dict(
  DESCRIPTOR = _HOTTHREADINFO,
  __module__ = 'tbclient.HotThreadInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.HotThreadInfo)
  ))
_sym_db.RegisterMessage(HotThreadInfo)


# @@protoc_insertion_point(module_scope)
