# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/LastViewFeeds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/LastViewFeeds.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/LastViewFeeds.proto\x12\x08tbclient\"\x1d\n\rLastViewFeeds\x12\x0c\n\x04live\x18\x01 \x03(\r')
)




_LASTVIEWFEEDS = _descriptor.Descriptor(
  name='LastViewFeeds',
  full_name='tbclient.LastViewFeeds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='live', full_name='tbclient.LastViewFeeds.live', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['LastViewFeeds'] = _LASTVIEWFEEDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LastViewFeeds = _reflection.GeneratedProtocolMessageType('LastViewFeeds', (_message.Message,), dict(
  DESCRIPTOR = _LASTVIEWFEEDS,
  __module__ = 'tbclient.LastViewFeeds_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.LastViewFeeds)
  ))
_sym_db.RegisterMessage(LastViewFeeds)


# @@protoc_insertion_point(module_scope)
