# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/Lbs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/Lbs.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x12tbclient/Lbs.proto\x12\x08tbclient\"9\n\x03Lbs\x12\x0b\n\x03lat\x18\x01 \x01(\t\x12\x0b\n\x03lng\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\n\n\x02sn\x18\x04 \x01(\t')
)




_LBS = _descriptor.Descriptor(
  name='Lbs',
  full_name='tbclient.Lbs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='tbclient.Lbs.lat', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='tbclient.Lbs.lng', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='tbclient.Lbs.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn', full_name='tbclient.Lbs.sn', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Lbs'] = _LBS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lbs = _reflection.GeneratedProtocolMessageType('Lbs', (_message.Message,), dict(
  DESCRIPTOR = _LBS,
  __module__ = 'tbclient.Lbs_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.Lbs)
  ))
_sym_db.RegisterMessage(Lbs)


# @@protoc_insertion_point(module_scope)
