# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/LikeForumInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/LikeForumInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/LikeForumInfo.proto\x12\x08tbclient\"5\n\rLikeForumInfo\x12\x10\n\x08\x66orum_id\x18\x02 \x01(\x04\x12\x12\n\nforum_name\x18\x01 \x01(\t')
)




_LIKEFORUMINFO = _descriptor.Descriptor(
  name='LikeForumInfo',
  full_name='tbclient.LikeForumInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forum_id', full_name='tbclient.LikeForumInfo.forum_id', index=0,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forum_name', full_name='tbclient.LikeForumInfo.forum_name', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['LikeForumInfo'] = _LIKEFORUMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LikeForumInfo = _reflection.GeneratedProtocolMessageType('LikeForumInfo', (_message.Message,), dict(
  DESCRIPTOR = _LIKEFORUMINFO,
  __module__ = 'tbclient.LikeForumInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.LikeForumInfo)
  ))
_sym_db.RegisterMessage(LikeForumInfo)


# @@protoc_insertion_point(module_scope)
