# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/LiveCoverStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/LiveCoverStatus.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1etbclient/LiveCoverStatus.proto\x12\x08tbclient\"5\n\x0fLiveCoverStatus\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nstatus_num\x18\x01 \x01(\x05')
)




_LIVECOVERSTATUS = _descriptor.Descriptor(
  name='LiveCoverStatus',
  full_name='tbclient.LiveCoverStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tbclient.LiveCoverStatus.status', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_num', full_name='tbclient.LiveCoverStatus.status_num', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['LiveCoverStatus'] = _LIVECOVERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LiveCoverStatus = _reflection.GeneratedProtocolMessageType('LiveCoverStatus', (_message.Message,), dict(
  DESCRIPTOR = _LIVECOVERSTATUS,
  __module__ = 'tbclient.LiveCoverStatus_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.LiveCoverStatus)
  ))
_sym_db.RegisterMessage(LiveCoverStatus)


# @@protoc_insertion_point(module_scope)
