# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/LotteryRegular.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/LotteryRegular.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1dtbclient/LotteryRegular.proto\x12\x08tbclient\"1\n\x0eLotteryRegular\x12\x0e\n\x06\x63hange\x18\x02 \x03(\x05\x12\x0f\n\x07regular\x18\x01 \x01(\t')
)




_LOTTERYREGULAR = _descriptor.Descriptor(
  name='LotteryRegular',
  full_name='tbclient.LotteryRegular',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='change', full_name='tbclient.LotteryRegular.change', index=0,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regular', full_name='tbclient.LotteryRegular.regular', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['LotteryRegular'] = _LOTTERYREGULAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LotteryRegular = _reflection.GeneratedProtocolMessageType('LotteryRegular', (_message.Message,), dict(
  DESCRIPTOR = _LOTTERYREGULAR,
  __module__ = 'tbclient.LotteryRegular_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.LotteryRegular)
  ))
_sym_db.RegisterMessage(LotteryRegular)


# @@protoc_insertion_point(module_scope)
