# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/ManagerApplyInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/ManagerApplyInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/ManagerApplyInfo.proto\x12\x08tbclient\"e\n\x10ManagerApplyInfo\x12\x1c\n\x14manager_apply_status\x18\x03 \x01(\x05\x12\x19\n\x11manager_apply_url\x18\x02 \x01(\t\x12\x18\n\x10manager_left_num\x18\x01 \x01(\x05')
)




_MANAGERAPPLYINFO = _descriptor.Descriptor(
  name='ManagerApplyInfo',
  full_name='tbclient.ManagerApplyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='manager_apply_status', full_name='tbclient.ManagerApplyInfo.manager_apply_status', index=0,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manager_apply_url', full_name='tbclient.ManagerApplyInfo.manager_apply_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manager_left_num', full_name='tbclient.ManagerApplyInfo.manager_left_num', index=2,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['ManagerApplyInfo'] = _MANAGERAPPLYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ManagerApplyInfo = _reflection.GeneratedProtocolMessageType('ManagerApplyInfo', (_message.Message,), dict(
  DESCRIPTOR = _MANAGERAPPLYINFO,
  __module__ = 'tbclient.ManagerApplyInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ManagerApplyInfo)
  ))
_sym_db.RegisterMessage(ManagerApplyInfo)


# @@protoc_insertion_point(module_scope)
