# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/ModuleInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import ThreadModule_pb2 as tbclient_dot_ThreadModule__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/ModuleInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x19tbclient/ModuleInfo.proto\x12\x08tbclient\x1a\x1btbclient/ThreadModule.proto\"p\n\nModuleInfo\x12\x16\n\x0emax_module_num\x18\x02 \x01(\x05\x12\x1d\n\x15max_module_thread_num\x18\x03 \x01(\x05\x12+\n\x0bmodule_list\x18\x01 \x03(\x0b\x32\x16.tbclient.ThreadModule')
  ,
  dependencies=[tbclient_dot_ThreadModule__pb2.DESCRIPTOR,])




_MODULEINFO = _descriptor.Descriptor(
  name='ModuleInfo',
  full_name='tbclient.ModuleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_module_num', full_name='tbclient.ModuleInfo.max_module_num', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_module_thread_num', full_name='tbclient.ModuleInfo.max_module_thread_num', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module_list', full_name='tbclient.ModuleInfo.module_list', index=2,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=180,
)

_MODULEINFO.fields_by_name['module_list'].message_type = tbclient_dot_ThreadModule__pb2._THREADMODULE
DESCRIPTOR.message_types_by_name['ModuleInfo'] = _MODULEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModuleInfo = _reflection.GeneratedProtocolMessageType('ModuleInfo', (_message.Message,), dict(
  DESCRIPTOR = _MODULEINFO,
  __module__ = 'tbclient.ModuleInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ModuleInfo)
  ))
_sym_db.RegisterMessage(ModuleInfo)


# @@protoc_insertion_point(module_scope)
