# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/MparrProps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import AvatarFrame_pb2 as tbclient_dot_AvatarFrame__pb2
from tbclient import Level_pb2 as tbclient_dot_Level__pb2
from tbclient import Portrait_pb2 as tbclient_dot_Portrait__pb2
from tbclient import Props_pb2 as tbclient_dot_Props__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/MparrProps.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x19tbclient/MparrProps.proto\x12\x08tbclient\x1a\x1atbclient/AvatarFrame.proto\x1a\x14tbclient/Level.proto\x1a\x17tbclient/Portrait.proto\x1a\x14tbclient/Props.proto\"\x9e\x01\n\nMparrProps\x12*\n\x0b\x61vatarframe\x18\x01 \x01(\x0b\x32\x15.tbclient.AvatarFrame\x12\x1e\n\x05level\x18\x03 \x01(\x0b\x32\x0f.tbclient.Level\x12$\n\x08portrait\x18\x02 \x01(\x0b\x32\x12.tbclient.Portrait\x12\x1e\n\x05props\x18\x04 \x03(\x0b\x32\x0f.tbclient.Props')
  ,
  dependencies=[tbclient_dot_AvatarFrame__pb2.DESCRIPTOR,tbclient_dot_Level__pb2.DESCRIPTOR,tbclient_dot_Portrait__pb2.DESCRIPTOR,tbclient_dot_Props__pb2.DESCRIPTOR,])




_MPARRPROPS = _descriptor.Descriptor(
  name='MparrProps',
  full_name='tbclient.MparrProps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='avatarframe', full_name='tbclient.MparrProps.avatarframe', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='tbclient.MparrProps.level', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portrait', full_name='tbclient.MparrProps.portrait', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props', full_name='tbclient.MparrProps.props', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=295,
)

_MPARRPROPS.fields_by_name['avatarframe'].message_type = tbclient_dot_AvatarFrame__pb2._AVATARFRAME
_MPARRPROPS.fields_by_name['level'].message_type = tbclient_dot_Level__pb2._LEVEL
_MPARRPROPS.fields_by_name['portrait'].message_type = tbclient_dot_Portrait__pb2._PORTRAIT
_MPARRPROPS.fields_by_name['props'].message_type = tbclient_dot_Props__pb2._PROPS
DESCRIPTOR.message_types_by_name['MparrProps'] = _MPARRPROPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MparrProps = _reflection.GeneratedProtocolMessageType('MparrProps', (_message.Message,), dict(
  DESCRIPTOR = _MPARRPROPS,
  __module__ = 'tbclient.MparrProps_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.MparrProps)
  ))
_sym_db.RegisterMessage(MparrProps)


# @@protoc_insertion_point(module_scope)
