# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/NaGuide.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import RecGuide_pb2 as tbclient_dot_RecGuide__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/NaGuide.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x16tbclient/NaGuide.proto\x12\x08tbclient\x1a\x17tbclient/RecGuide.proto\"A\n\x07NaGuide\x12\x10\n\x08\x64wnl_url\x18\x01 \x01(\t\x12$\n\x08rec_info\x18\x02 \x03(\x0b\x32\x12.tbclient.RecGuide')
  ,
  dependencies=[tbclient_dot_RecGuide__pb2.DESCRIPTOR,])




_NAGUIDE = _descriptor.Descriptor(
  name='NaGuide',
  full_name='tbclient.NaGuide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dwnl_url', full_name='tbclient.NaGuide.dwnl_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rec_info', full_name='tbclient.NaGuide.rec_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=126,
)

_NAGUIDE.fields_by_name['rec_info'].message_type = tbclient_dot_RecGuide__pb2._RECGUIDE
DESCRIPTOR.message_types_by_name['NaGuide'] = _NAGUIDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NaGuide = _reflection.GeneratedProtocolMessageType('NaGuide', (_message.Message,), dict(
  DESCRIPTOR = _NAGUIDE,
  __module__ = 'tbclient.NaGuide_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.NaGuide)
  ))
_sym_db.RegisterMessage(NaGuide)


# @@protoc_insertion_point(module_scope)
