# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/NativeApp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/NativeApp.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x18tbclient/NativeApp.proto\x12\x08tbclient\"[\n\tNativeApp\x12\x14\n\x0c\x64ownload_and\x18\x03 \x01(\t\x12\x14\n\x0c\x64ownload_ios\x18\x04 \x01(\t\x12\x10\n\x08jump_and\x18\x01 \x01(\t\x12\x10\n\x08jump_ios\x18\x02 \x01(\t')
)




_NATIVEAPP = _descriptor.Descriptor(
  name='NativeApp',
  full_name='tbclient.NativeApp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='download_and', full_name='tbclient.NativeApp.download_and', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='download_ios', full_name='tbclient.NativeApp.download_ios', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jump_and', full_name='tbclient.NativeApp.jump_and', index=2,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jump_ios', full_name='tbclient.NativeApp.jump_ios', index=3,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['NativeApp'] = _NATIVEAPP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NativeApp = _reflection.GeneratedProtocolMessageType('NativeApp', (_message.Message,), dict(
  DESCRIPTOR = _NATIVEAPP,
  __module__ = 'tbclient.NativeApp_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.NativeApp)
  ))
_sym_db.RegisterMessage(NativeApp)


# @@protoc_insertion_point(module_scope)
