# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/NewParrScores.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/NewParrScores.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/NewParrScores.proto\x12\x08tbclient\"K\n\rNewParrScores\x12\x0f\n\x07i_total\x18\x03 \x01(\x04\x12\x14\n\x0cscores_total\x18\x01 \x01(\x04\x12\x13\n\x0bupdate_time\x18\x02 \x01(\r')
)




_NEWPARRSCORES = _descriptor.Descriptor(
  name='NewParrScores',
  full_name='tbclient.NewParrScores',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='i_total', full_name='tbclient.NewParrScores.i_total', index=0,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores_total', full_name='tbclient.NewParrScores.scores_total', index=1,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='tbclient.NewParrScores.update_time', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['NewParrScores'] = _NEWPARRSCORES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewParrScores = _reflection.GeneratedProtocolMessageType('NewParrScores', (_message.Message,), dict(
  DESCRIPTOR = _NEWPARRSCORES,
  __module__ = 'tbclient.NewParrScores_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.NewParrScores)
  ))
_sym_db.RegisterMessage(NewParrScores)


# @@protoc_insertion_point(module_scope)
