# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/NoticeInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/NoticeInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x19tbclient/NoticeInfo.proto\x12\x08tbclient\":\n\nNoticeInfo\x12\x0e\n\x06notice\x18\x01 \x01(\t\x12\x1c\n\x14pullCommentFrequence\x18\x02 \x01(\x05')
)




_NOTICEINFO = _descriptor.Descriptor(
  name='NoticeInfo',
  full_name='tbclient.NoticeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notice', full_name='tbclient.NoticeInfo.notice', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pullCommentFrequence', full_name='tbclient.NoticeInfo.pullCommentFrequence', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['NoticeInfo'] = _NOTICEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NoticeInfo = _reflection.GeneratedProtocolMessageType('NoticeInfo', (_message.Message,), dict(
  DESCRIPTOR = _NOTICEINFO,
  __module__ = 'tbclient.NoticeInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.NoticeInfo)
  ))
_sym_db.RegisterMessage(NoticeInfo)


# @@protoc_insertion_point(module_scope)
