# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/NovelFansInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/NovelFansInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/NovelFansInfo.proto\x12\x08tbclient\"F\n\rNovelFansInfo\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x12\n\nlevel_icon\x18\x03 \x01(\t\x12\x12\n\nlevel_name\x18\x02 \x01(\t')
)




_NOVELFANSINFO = _descriptor.Descriptor(
  name='NovelFansInfo',
  full_name='tbclient.NovelFansInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='tbclient.NovelFansInfo.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level_icon', full_name='tbclient.NovelFansInfo.level_icon', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level_name', full_name='tbclient.NovelFansInfo.level_name', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['NovelFansInfo'] = _NOVELFANSINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NovelFansInfo = _reflection.GeneratedProtocolMessageType('NovelFansInfo', (_message.Message,), dict(
  DESCRIPTOR = _NOVELFANSINFO,
  __module__ = 'tbclient.NovelFansInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.NovelFansInfo)
  ))
_sym_db.RegisterMessage(NovelFansInfo)


# @@protoc_insertion_point(module_scope)
