# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/PbHotPost.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import HotPost_pb2 as tbclient_dot_HotPost__pb2
from tbclient import Post_pb2 as tbclient_dot_Post__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/PbHotPost.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x18tbclient/PbHotPost.proto\x12\x08tbclient\x1a\x16tbclient/HotPost.proto\x1a\x13tbclient/Post.proto\"\x86\x01\n\tPbHotPost\x12(\n\rhot_post_list\x18\x04 \x03(\x0b\x32\x11.tbclient.HotPost\x12\x15\n\rneed_hot_post\x18\x02 \x01(\x05\x12\x15\n\rneed_post_zan\x18\x03 \x01(\x05\x12!\n\tpost_list\x18\x01 \x03(\x0b\x32\x0e.tbclient.Post')
  ,
  dependencies=[tbclient_dot_HotPost__pb2.DESCRIPTOR,tbclient_dot_Post__pb2.DESCRIPTOR,])




_PBHOTPOST = _descriptor.Descriptor(
  name='PbHotPost',
  full_name='tbclient.PbHotPost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hot_post_list', full_name='tbclient.PbHotPost.hot_post_list', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_hot_post', full_name='tbclient.PbHotPost.need_hot_post', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_post_zan', full_name='tbclient.PbHotPost.need_post_zan', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_list', full_name='tbclient.PbHotPost.post_list', index=3,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=218,
)

_PBHOTPOST.fields_by_name['hot_post_list'].message_type = tbclient_dot_HotPost__pb2._HOTPOST
_PBHOTPOST.fields_by_name['post_list'].message_type = tbclient_dot_Post__pb2._POST
DESCRIPTOR.message_types_by_name['PbHotPost'] = _PBHOTPOST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbHotPost = _reflection.GeneratedProtocolMessageType('PbHotPost', (_message.Message,), dict(
  DESCRIPTOR = _PBHOTPOST,
  __module__ = 'tbclient.PbHotPost_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.PbHotPost)
  ))
_sym_db.RegisterMessage(PbHotPost)


# @@protoc_insertion_point(module_scope)
