# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/PopInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/PopInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x16tbclient/PopInfo.proto\x12\x08tbclient\"q\n\x07PopInfo\x12\x12\n\nahead_info\x18\x04 \x01(\t\x12\x11\n\tahead_url\x18\x05 \x01(\t\x12\x0e\n\x06if_pop\x18\x01 \x01(\x05\x12\x0f\n\x07ok_info\x18\x06 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07v_title\x18\x03 \x01(\t')
)




_POPINFO = _descriptor.Descriptor(
  name='PopInfo',
  full_name='tbclient.PopInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ahead_info', full_name='tbclient.PopInfo.ahead_info', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ahead_url', full_name='tbclient.PopInfo.ahead_url', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='if_pop', full_name='tbclient.PopInfo.if_pop', index=2,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ok_info', full_name='tbclient.PopInfo.ok_info', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.PopInfo.title', index=4,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_title', full_name='tbclient.PopInfo.v_title', index=5,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['PopInfo'] = _POPINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PopInfo = _reflection.GeneratedProtocolMessageType('PopInfo', (_message.Message,), dict(
  DESCRIPTOR = _POPINFO,
  __module__ = 'tbclient.PopInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.PopInfo)
  ))
_sym_db.RegisterMessage(PopInfo)


# @@protoc_insertion_point(module_scope)
