# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/PostInfoContent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import Abstract_pb2 as tbclient_dot_Abstract__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/PostInfoContent.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1etbclient/PostInfoContent.proto\x12\x08tbclient\x1a\x17tbclient/Abstract.proto\"t\n\x0fPostInfoContent\x12\x13\n\x0b\x63reate_time\x18\x02 \x01(\x04\x12(\n\x0cpost_content\x18\x01 \x03(\x0b\x32\x12.tbclient.Abstract\x12\x0f\n\x07post_id\x18\x04 \x01(\x04\x12\x11\n\tpost_type\x18\x03 \x01(\x04')
  ,
  dependencies=[tbclient_dot_Abstract__pb2.DESCRIPTOR,])




_POSTINFOCONTENT = _descriptor.Descriptor(
  name='PostInfoContent',
  full_name='tbclient.PostInfoContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='create_time', full_name='tbclient.PostInfoContent.create_time', index=0,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_content', full_name='tbclient.PostInfoContent.post_content', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_id', full_name='tbclient.PostInfoContent.post_id', index=2,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_type', full_name='tbclient.PostInfoContent.post_type', index=3,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=185,
)

_POSTINFOCONTENT.fields_by_name['post_content'].message_type = tbclient_dot_Abstract__pb2._ABSTRACT
DESCRIPTOR.message_types_by_name['PostInfoContent'] = _POSTINFOCONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PostInfoContent = _reflection.GeneratedProtocolMessageType('PostInfoContent', (_message.Message,), dict(
  DESCRIPTOR = _POSTINFOCONTENT,
  __module__ = 'tbclient.PostInfoContent_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.PostInfoContent)
  ))
_sym_db.RegisterMessage(PostInfoContent)


# @@protoc_insertion_point(module_scope)
