# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/Props.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/Props.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x14tbclient/Props.proto\x12\x08tbclient\"\xa5\x02\n\x05Props\x12\r\n\x05_word\x18\x0e \x03(\t\x12\x10\n\x08\x65nd_time\x18\x07 \x01(\t\x12\x16\n\x0e\x65xpired_notify\x18\x0c \x01(\t\x12\x17\n\x0f\x65xpiring_notify\x18\x0b \x01(\t\x12\x10\n\x08left_num\x18\x04 \x01(\x05\x12\x0e\n\x06notice\x18\x08 \x01(\t\x12\x0b\n\x03num\x18\x06 \x01(\x05\x12\x13\n\x0bopen_status\x18\n \x01(\t\x12\x0f\n\x07pattern\x18\x0f \x03(\t\x12\x16\n\x0eprops_category\x18\x03 \x01(\t\x12\x10\n\x08props_id\x18\x01 \x01(\x05\x12\x12\n\nprops_type\x18\x02 \x01(\t\x12\r\n\x05title\x18\r \x01(\t\x12\x13\n\x0bupdate_time\x18\t \x01(\x05\x12\x13\n\x0bused_status\x18\x05 \x01(\t')
)




_PROPS = _descriptor.Descriptor(
  name='Props',
  full_name='tbclient.Props',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_word', full_name='tbclient.Props._word', index=0,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='tbclient.Props.end_time', index=1,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expired_notify', full_name='tbclient.Props.expired_notify', index=2,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiring_notify', full_name='tbclient.Props.expiring_notify', index=3,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_num', full_name='tbclient.Props.left_num', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notice', full_name='tbclient.Props.notice', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='tbclient.Props.num', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_status', full_name='tbclient.Props.open_status', index=7,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='tbclient.Props.pattern', index=8,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props_category', full_name='tbclient.Props.props_category', index=9,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props_id', full_name='tbclient.Props.props_id', index=10,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props_type', full_name='tbclient.Props.props_type', index=11,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.Props.title', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='tbclient.Props.update_time', index=13,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='used_status', full_name='tbclient.Props.used_status', index=14,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=328,
)

DESCRIPTOR.message_types_by_name['Props'] = _PROPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Props = _reflection.GeneratedProtocolMessageType('Props', (_message.Message,), dict(
  DESCRIPTOR = _PROPS,
  __module__ = 'tbclient.Props_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.Props)
  ))
_sym_db.RegisterMessage(Props)


# @@protoc_insertion_point(module_scope)
