# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/RecomTopicList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/RecomTopicList.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1dtbclient/RecomTopicList.proto\x12\x08tbclient\"\x8d\x01\n\x0eRecomTopicList\x12\x13\n\x0b\x64iscuss_num\x18\x04 \x01(\x04\x12\x0b\n\x03tag\x18\x05 \x01(\r\x12\x12\n\ntopic_desc\x18\x06 \x01(\t\x12\x10\n\x08topic_id\x18\x01 \x01(\x04\x12\x12\n\ntopic_name\x18\x02 \x01(\t\x12\x11\n\ttopic_pic\x18\x07 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\r')
)




_RECOMTOPICLIST = _descriptor.Descriptor(
  name='RecomTopicList',
  full_name='tbclient.RecomTopicList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='discuss_num', full_name='tbclient.RecomTopicList.discuss_num', index=0,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='tbclient.RecomTopicList.tag', index=1,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_desc', full_name='tbclient.RecomTopicList.topic_desc', index=2,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_id', full_name='tbclient.RecomTopicList.topic_id', index=3,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_name', full_name='tbclient.RecomTopicList.topic_name', index=4,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_pic', full_name='tbclient.RecomTopicList.topic_pic', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='tbclient.RecomTopicList.type', index=6,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['RecomTopicList'] = _RECOMTOPICLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecomTopicList = _reflection.GeneratedProtocolMessageType('RecomTopicList', (_message.Message,), dict(
  DESCRIPTOR = _RECOMTOPICLIST,
  __module__ = 'tbclient.RecomTopicList_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.RecomTopicList)
  ))
_sym_db.RegisterMessage(RecomTopicList)


# @@protoc_insertion_point(module_scope)
