# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/RecomTopicInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import RecomTopicList_pb2 as tbclient_dot_RecomTopicList__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/RecomTopicInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1dtbclient/RecomTopicInfo.proto\x12\x08tbclient\x1a\x1dtbclient/RecomTopicList.proto\"S\n\x0eRecomTopicInfo\x12\x13\n\x0brecom_title\x18\x01 \x01(\t\x12,\n\ntopic_list\x18\x02 \x03(\x0b\x32\x18.tbclient.RecomTopicList')
  ,
  dependencies=[tbclient_dot_RecomTopicList__pb2.DESCRIPTOR,])




_RECOMTOPICINFO = _descriptor.Descriptor(
  name='RecomTopicInfo',
  full_name='tbclient.RecomTopicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recom_title', full_name='tbclient.RecomTopicInfo.recom_title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_list', full_name='tbclient.RecomTopicInfo.topic_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=157,
)

_RECOMTOPICINFO.fields_by_name['topic_list'].message_type = tbclient_dot_RecomTopicList__pb2._RECOMTOPICLIST
DESCRIPTOR.message_types_by_name['RecomTopicInfo'] = _RECOMTOPICINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecomTopicInfo = _reflection.GeneratedProtocolMessageType('RecomTopicInfo', (_message.Message,), dict(
  DESCRIPTOR = _RECOMTOPICINFO,
  __module__ = 'tbclient.RecomTopicInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.RecomTopicInfo)
  ))
_sym_db.RegisterMessage(RecomTopicInfo)


# @@protoc_insertion_point(module_scope)
