# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/SchoolRecomUserInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/SchoolRecomUserInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\"tbclient/SchoolRecomUserInfo.proto\x12\x08tbclient\"h\n\x13SchoolRecomUserInfo\x12\x11\n\tinstitute\x18\x04 \x01(\t\x12\x10\n\x08is_liked\x18\x05 \x01(\r\x12\x10\n\x08portrait\x18\x03 \x01(\t\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\r\n\x05uname\x18\x02 \x01(\t')
)




_SCHOOLRECOMUSERINFO = _descriptor.Descriptor(
  name='SchoolRecomUserInfo',
  full_name='tbclient.SchoolRecomUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='institute', full_name='tbclient.SchoolRecomUserInfo.institute', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_liked', full_name='tbclient.SchoolRecomUserInfo.is_liked', index=1,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portrait', full_name='tbclient.SchoolRecomUserInfo.portrait', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='tbclient.SchoolRecomUserInfo.uid', index=3,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uname', full_name='tbclient.SchoolRecomUserInfo.uname', index=4,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['SchoolRecomUserInfo'] = _SCHOOLRECOMUSERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchoolRecomUserInfo = _reflection.GeneratedProtocolMessageType('SchoolRecomUserInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCHOOLRECOMUSERINFO,
  __module__ = 'tbclient.SchoolRecomUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.SchoolRecomUserInfo)
  ))
_sym_db.RegisterMessage(SchoolRecomUserInfo)


# @@protoc_insertion_point(module_scope)
