# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/SimpleThreadInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import Abstract_pb2 as tbclient_dot_Abstract__pb2
from tbclient import Zan_pb2 as tbclient_dot_Zan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/SimpleThreadInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/SimpleThreadInfo.proto\x12\x08tbclient\x1a\x17tbclient/Abstract.proto\x1a\x12tbclient/Zan.proto\"\xb0\x01\n\x10SimpleThreadInfo\x12%\n\t_abstract\x18\x05 \x03(\x0b\x32\x12.tbclient.Abstract\x12\x15\n\rlast_time_int\x18\x04 \x01(\x05\x12\x11\n\treply_num\x18\x03 \x01(\x05\x12\x13\n\x0bthread_type\x18\x07 \x01(\x04\x12\x0b\n\x03tid\x18\x01 \x01(\x04\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1a\n\x03zan\x18\x06 \x01(\x0b\x32\r.tbclient.Zan')
  ,
  dependencies=[tbclient_dot_Abstract__pb2.DESCRIPTOR,tbclient_dot_Zan__pb2.DESCRIPTOR,])




_SIMPLETHREADINFO = _descriptor.Descriptor(
  name='SimpleThreadInfo',
  full_name='tbclient.SimpleThreadInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_abstract', full_name='tbclient.SimpleThreadInfo._abstract', index=0,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_time_int', full_name='tbclient.SimpleThreadInfo.last_time_int', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reply_num', full_name='tbclient.SimpleThreadInfo.reply_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_type', full_name='tbclient.SimpleThreadInfo.thread_type', index=3,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tid', full_name='tbclient.SimpleThreadInfo.tid', index=4,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.SimpleThreadInfo.title', index=5,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zan', full_name='tbclient.SimpleThreadInfo.zan', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=267,
)

_SIMPLETHREADINFO.fields_by_name['_abstract'].message_type = tbclient_dot_Abstract__pb2._ABSTRACT
_SIMPLETHREADINFO.fields_by_name['zan'].message_type = tbclient_dot_Zan__pb2._ZAN
DESCRIPTOR.message_types_by_name['SimpleThreadInfo'] = _SIMPLETHREADINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleThreadInfo = _reflection.GeneratedProtocolMessageType('SimpleThreadInfo', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLETHREADINFO,
  __module__ = 'tbclient.SimpleThreadInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.SimpleThreadInfo)
  ))
_sym_db.RegisterMessage(SimpleThreadInfo)


# @@protoc_insertion_point(module_scope)
