# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/Superscript.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/Superscript.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1atbclient/Superscript.proto\x12\x08tbclient\"*\n\x0bSuperscript\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\t')
)




_SUPERSCRIPT = _descriptor.Descriptor(
  name='Superscript',
  full_name='tbclient.Superscript',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='tbclient.Superscript.color', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='tbclient.Superscript.desc', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Superscript'] = _SUPERSCRIPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Superscript = _reflection.GeneratedProtocolMessageType('Superscript', (_message.Message,), dict(
  DESCRIPTOR = _SUPERSCRIPT,
  __module__ = 'tbclient.Superscript_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.Superscript)
  ))
_sym_db.RegisterMessage(Superscript)


# @@protoc_insertion_point(module_scope)
