# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/TbBookrack.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import BookInfo_pb2 as tbclient_dot_BookInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/TbBookrack.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x19tbclient/TbBookrack.proto\x12\x08tbclient\x1a\x17tbclient/BookInfo.proto\"|\n\nTbBookrack\x12%\n\tbook_list\x18\x03 \x03(\x0b\x32\x12.tbclient.BookInfo\x12\x10\n\x08\x62ooktown\x18\x01 \x01(\t\x12\x0c\n\x04icon\x18\x05 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\r\x12\x0b\n\x03tip\x18\x06 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t')
  ,
  dependencies=[tbclient_dot_BookInfo__pb2.DESCRIPTOR,])




_TBBOOKRACK = _descriptor.Descriptor(
  name='TbBookrack',
  full_name='tbclient.TbBookrack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_list', full_name='tbclient.TbBookrack.book_list', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='booktown', full_name='tbclient.TbBookrack.booktown', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='tbclient.TbBookrack.icon', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='tbclient.TbBookrack.num', index=3,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tip', full_name='tbclient.TbBookrack.tip', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.TbBookrack.title', index=5,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=188,
)

_TBBOOKRACK.fields_by_name['book_list'].message_type = tbclient_dot_BookInfo__pb2._BOOKINFO
DESCRIPTOR.message_types_by_name['TbBookrack'] = _TBBOOKRACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TbBookrack = _reflection.GeneratedProtocolMessageType('TbBookrack', (_message.Message,), dict(
  DESCRIPTOR = _TBBOOKRACK,
  __module__ = 'tbclient.TbBookrack_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.TbBookrack)
  ))
_sym_db.RegisterMessage(TbBookrack)


# @@protoc_insertion_point(module_scope)
