# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/ThemePendantProp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/ThemePendantProp.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/ThemePendantProp.proto\x12\x08tbclient\"3\n\x10ThemePendantProp\x12\x10\n\x08props_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t')
)




_THEMEPENDANTPROP = _descriptor.Descriptor(
  name='ThemePendantProp',
  full_name='tbclient.ThemePendantProp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='props_id', full_name='tbclient.ThemePendantProp.props_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.ThemePendantProp.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['ThemePendantProp'] = _THEMEPENDANTPROP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThemePendantProp = _reflection.GeneratedProtocolMessageType('ThemePendantProp', (_message.Message,), dict(
  DESCRIPTOR = _THEMEPENDANTPROP,
  __module__ = 'tbclient.ThemePendantProp_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ThemePendantProp)
  ))
_sym_db.RegisterMessage(ThemePendantProp)


# @@protoc_insertion_point(module_scope)
