# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/TshowInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/TshowInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x18tbclient/TshowInfo.proto\x12\x08tbclient\"4\n\tTshowInfo\x12\x0c\n\x04icon\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t')
)




_TSHOWINFO = _descriptor.Descriptor(
  name='TshowInfo',
  full_name='tbclient.TshowInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='icon', full_name='tbclient.TshowInfo.icon', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='tbclient.TshowInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='tbclient.TshowInfo.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['TshowInfo'] = _TSHOWINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TshowInfo = _reflection.GeneratedProtocolMessageType('TshowInfo', (_message.Message,), dict(
  DESCRIPTOR = _TSHOWINFO,
  __module__ = 'tbclient.TshowInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.TshowInfo)
  ))
_sym_db.RegisterMessage(TshowInfo)


# @@protoc_insertion_point(module_scope)
