# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/TWGuideDesc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/TWGuideDesc.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1atbclient/TWGuideDesc.proto\x12\x08tbclient\"9\n\x0bTWGuideDesc\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\r\n\x05order\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t')
)




_TWGUIDEDESC = _descriptor.Descriptor(
  name='TWGuideDesc',
  full_name='tbclient.TWGuideDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link', full_name='tbclient.TWGuideDesc.link', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='tbclient.TWGuideDesc.order', index=1,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.TWGuideDesc.title', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['TWGuideDesc'] = _TWGUIDEDESC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TWGuideDesc = _reflection.GeneratedProtocolMessageType('TWGuideDesc', (_message.Message,), dict(
  DESCRIPTOR = _TWGUIDEDESC,
  __module__ = 'tbclient.TWGuideDesc_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.TWGuideDesc)
  ))
_sym_db.RegisterMessage(TWGuideDesc)


# @@protoc_insertion_point(module_scope)
