# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/TwZhiBoUser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/TwZhiBoUser.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1atbclient/TwZhiBoUser.proto\x12\x08tbclient\"L\n\x0bTwZhiBoUser\x12\x14\n\x0c\x61nchor_level\x18\x01 \x01(\r\x12\x10\n\x08\x66ield_ex\x18\x03 \x01(\t\x12\x15\n\rin_black_list\x18\x02 \x01(\r')
)




_TWZHIBOUSER = _descriptor.Descriptor(
  name='TwZhiBoUser',
  full_name='tbclient.TwZhiBoUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anchor_level', full_name='tbclient.TwZhiBoUser.anchor_level', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_ex', full_name='tbclient.TwZhiBoUser.field_ex', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_black_list', full_name='tbclient.TwZhiBoUser.in_black_list', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['TwZhiBoUser'] = _TWZHIBOUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TwZhiBoUser = _reflection.GeneratedProtocolMessageType('TwZhiBoUser', (_message.Message,), dict(
  DESCRIPTOR = _TWZHIBOUSER,
  __module__ = 'tbclient.TwZhiBoUser_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.TwZhiBoUser)
  ))
_sym_db.RegisterMessage(TwZhiBoUser)


# @@protoc_insertion_point(module_scope)
