# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/UserStoryAlaLiveInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import AlaLiveInfo_pb2 as tbclient_dot_AlaLiveInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/UserStoryAlaLiveInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n#tbclient/UserStoryAlaLiveInfo.proto\x12\x08tbclient\x1a\x1atbclient/AlaLiveInfo.proto\"\xd2\x04\n\x14UserStoryAlaLiveInfo\x12\x11\n\tagree_num\x18\x1a \x01(\x03\x12\'\n\x08\x61la_info\x18\x1b \x01(\x0b\x32\x15.tbclient.AlaLiveInfo\x12\x15\n\rfirst_post_id\x18\x13 \x01(\x03\x12\x10\n\x08\x66orum_id\x18\x01 \x01(\x03\x12\x12\n\nforum_name\x18\x14 \x01(\t\x12\x10\n\x08\x66req_num\x18\x17 \x01(\x05\x12\x16\n\x0e\x66rom_thread_id\x18\x07 \x01(\x03\x12\x12\n\ngood_types\x18\x0c \x01(\x05\x12\x12\n\nis_deleted\x18\x12 \x01(\x05\x12\x1a\n\x12last_modified_time\x18\t \x01(\x05\x12\x19\n\x11last_post_deleted\x18\x16 \x01(\x05\x12\x14\n\x0clast_post_id\x18\x10 \x01(\x03\x12\x14\n\x0clast_user_id\x18\n \x01(\x03\x12\x14\n\x0clast_user_ip\x18\x0b \x01(\x05\x12\x0f\n\x07live_id\x18\x18 \x01(\x03\x12\x12\n\nphone_type\x18\x11 \x01(\x05\x12\x10\n\x08post_num\x18\x08 \x01(\x03\x12\x16\n\x0ethread_classes\x18\x0f \x01(\x05\x12\x11\n\tthread_id\x18\x02 \x01(\x03\x12\x14\n\x0cthread_types\x18\x0e \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x14\n\x0ctitle_prefix\x18\x15 \x01(\t\x12\x11\n\ttop_types\x18\r \x01(\x05\x12\x13\n\x0btstore_type\x18\x19 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\x03\x12\x0f\n\x07user_ip\x18\x05 \x01(\x05\x12\x0f\n\x07vote_id\x18\x06 \x01(\x03')
  ,
  dependencies=[tbclient_dot_AlaLiveInfo__pb2.DESCRIPTOR,])




_USERSTORYALALIVEINFO = _descriptor.Descriptor(
  name='UserStoryAlaLiveInfo',
  full_name='tbclient.UserStoryAlaLiveInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agree_num', full_name='tbclient.UserStoryAlaLiveInfo.agree_num', index=0,
      number=26, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ala_info', full_name='tbclient.UserStoryAlaLiveInfo.ala_info', index=1,
      number=27, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_post_id', full_name='tbclient.UserStoryAlaLiveInfo.first_post_id', index=2,
      number=19, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forum_id', full_name='tbclient.UserStoryAlaLiveInfo.forum_id', index=3,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forum_name', full_name='tbclient.UserStoryAlaLiveInfo.forum_name', index=4,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freq_num', full_name='tbclient.UserStoryAlaLiveInfo.freq_num', index=5,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_thread_id', full_name='tbclient.UserStoryAlaLiveInfo.from_thread_id', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='good_types', full_name='tbclient.UserStoryAlaLiveInfo.good_types', index=7,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_deleted', full_name='tbclient.UserStoryAlaLiveInfo.is_deleted', index=8,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_modified_time', full_name='tbclient.UserStoryAlaLiveInfo.last_modified_time', index=9,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_post_deleted', full_name='tbclient.UserStoryAlaLiveInfo.last_post_deleted', index=10,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_post_id', full_name='tbclient.UserStoryAlaLiveInfo.last_post_id', index=11,
      number=16, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_user_id', full_name='tbclient.UserStoryAlaLiveInfo.last_user_id', index=12,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_user_ip', full_name='tbclient.UserStoryAlaLiveInfo.last_user_ip', index=13,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live_id', full_name='tbclient.UserStoryAlaLiveInfo.live_id', index=14,
      number=24, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone_type', full_name='tbclient.UserStoryAlaLiveInfo.phone_type', index=15,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_num', full_name='tbclient.UserStoryAlaLiveInfo.post_num', index=16,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_classes', full_name='tbclient.UserStoryAlaLiveInfo.thread_classes', index=17,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='tbclient.UserStoryAlaLiveInfo.thread_id', index=18,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_types', full_name='tbclient.UserStoryAlaLiveInfo.thread_types', index=19,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.UserStoryAlaLiveInfo.title', index=20,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_prefix', full_name='tbclient.UserStoryAlaLiveInfo.title_prefix', index=21,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_types', full_name='tbclient.UserStoryAlaLiveInfo.top_types', index=22,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tstore_type', full_name='tbclient.UserStoryAlaLiveInfo.tstore_type', index=23,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tbclient.UserStoryAlaLiveInfo.user_id', index=24,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_ip', full_name='tbclient.UserStoryAlaLiveInfo.user_ip', index=25,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote_id', full_name='tbclient.UserStoryAlaLiveInfo.vote_id', index=26,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=672,
)

_USERSTORYALALIVEINFO.fields_by_name['ala_info'].message_type = tbclient_dot_AlaLiveInfo__pb2._ALALIVEINFO
DESCRIPTOR.message_types_by_name['UserStoryAlaLiveInfo'] = _USERSTORYALALIVEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserStoryAlaLiveInfo = _reflection.GeneratedProtocolMessageType('UserStoryAlaLiveInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERSTORYALALIVEINFO,
  __module__ = 'tbclient.UserStoryAlaLiveInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.UserStoryAlaLiveInfo)
  ))
_sym_db.RegisterMessage(UserStoryAlaLiveInfo)


# @@protoc_insertion_point(module_scope)
