# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/UserVideoChannelInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/UserVideoChannelInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n#tbclient/UserVideoChannelInfo.proto\x12\x08tbclient\"C\n\x14UserVideoChannelInfo\x12\x16\n\x0e\x66ollow_channel\x18\x02 \x01(\x05\x12\x13\n\x0bman_channel\x18\x01 \x01(\x05')
)




_USERVIDEOCHANNELINFO = _descriptor.Descriptor(
  name='UserVideoChannelInfo',
  full_name='tbclient.UserVideoChannelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='follow_channel', full_name='tbclient.UserVideoChannelInfo.follow_channel', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='man_channel', full_name='tbclient.UserVideoChannelInfo.man_channel', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['UserVideoChannelInfo'] = _USERVIDEOCHANNELINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserVideoChannelInfo = _reflection.GeneratedProtocolMessageType('UserVideoChannelInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERVIDEOCHANNELINFO,
  __module__ = 'tbclient.UserVideoChannelInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.UserVideoChannelInfo)
  ))
_sym_db.RegisterMessage(UserVideoChannelInfo)


# @@protoc_insertion_point(module_scope)
