# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/VDetailInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/VDetailInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1atbclient/VDetailInfo.proto\x12\x08tbclient\"P\n\x0bVDetailInfo\x12\x13\n\x0b\x64\x65tail_info\x18\x04 \x01(\t\x12\r\n\x05intro\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0c\n\x04v_id\x18\x01 \x01(\x03')
)




_VDETAILINFO = _descriptor.Descriptor(
  name='VDetailInfo',
  full_name='tbclient.VDetailInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detail_info', full_name='tbclient.VDetailInfo.detail_info', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intro', full_name='tbclient.VDetailInfo.intro', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tbclient.VDetailInfo.user_id', index=2,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_id', full_name='tbclient.VDetailInfo.v_id', index=3,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['VDetailInfo'] = _VDETAILINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VDetailInfo = _reflection.GeneratedProtocolMessageType('VDetailInfo', (_message.Message,), dict(
  DESCRIPTOR = _VDETAILINFO,
  __module__ = 'tbclient.VDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.VDetailInfo)
  ))
_sym_db.RegisterMessage(VDetailInfo)


# @@protoc_insertion_point(module_scope)
