# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/VideoChannelInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/VideoChannelInfo.proto',
  package='tbclient',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/VideoChannelInfo.proto\x12\x08tbclient\"T\n\x10VideoChannelInfo\x12\x16\n\x0e\x63hannel_avatar\x18\x03 \x01(\t\x12\x12\n\nchannel_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x63hannel_name\x18\x02 \x01(\t')
)




_VIDEOCHANNELINFO = _descriptor.Descriptor(
  name='VideoChannelInfo',
  full_name='tbclient.VideoChannelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_avatar', full_name='tbclient.VideoChannelInfo.channel_avatar', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='tbclient.VideoChannelInfo.channel_id', index=1,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='tbclient.VideoChannelInfo.channel_name', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['VideoChannelInfo'] = _VIDEOCHANNELINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoChannelInfo = _reflection.GeneratedProtocolMessageType('VideoChannelInfo', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOCHANNELINFO,
  __module__ = 'tbclient.VideoChannelInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.VideoChannelInfo)
  ))
_sym_db.RegisterMessage(VideoChannelInfo)


# @@protoc_insertion_point(module_scope)
