# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/PbPage/AdParam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/PbPage/AdParam.proto',
  package='tbclient.PbPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1dtbclient/PbPage/AdParam.proto\x12\x0ftbclient.PbPage\"4\n\x07\x41\x64Param\x12\x12\n\nload_count\x18\x01 \x01(\x05\x12\x15\n\rrefresh_count\x18\x02 \x01(\x05')
)




_ADPARAM = _descriptor.Descriptor(
  name='AdParam',
  full_name='tbclient.PbPage.AdParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='load_count', full_name='tbclient.PbPage.AdParam.load_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refresh_count', full_name='tbclient.PbPage.AdParam.refresh_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['AdParam'] = _ADPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdParam = _reflection.GeneratedProtocolMessageType('AdParam', (_message.Message,), dict(
  DESCRIPTOR = _ADPARAM,
  __module__ = 'tbclient.PbPage.AdParam_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.PbPage.AdParam)
  ))
_sym_db.RegisterMessage(AdParam)


# @@protoc_insertion_point(module_scope)
