# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/PbPage/NewsInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/PbPage/NewsInfo.proto',
  package='tbclient.PbPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1etbclient/PbPage/NewsInfo.proto\x12\x0ftbclient.PbPage\"\x8d\x01\n\x08NewsInfo\x12\x13\n\x0b\x62utton_text\x18\x07 \x01(\t\x12\x11\n\tnews_icon\x18\x05 \x01(\t\x12\x11\n\tnews_link\x18\x01 \x01(\t\x12\x11\n\tnews_type\x18\x04 \x01(\r\x12\x10\n\x08position\x18\x03 \x01(\r\x12\x10\n\x08subtitle\x18\x06 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t')
)




_NEWSINFO = _descriptor.Descriptor(
  name='NewsInfo',
  full_name='tbclient.PbPage.NewsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button_text', full_name='tbclient.PbPage.NewsInfo.button_text', index=0,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='news_icon', full_name='tbclient.PbPage.NewsInfo.news_icon', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='news_link', full_name='tbclient.PbPage.NewsInfo.news_link', index=2,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='news_type', full_name='tbclient.PbPage.NewsInfo.news_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='tbclient.PbPage.NewsInfo.position', index=4,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtitle', full_name='tbclient.PbPage.NewsInfo.subtitle', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='tbclient.PbPage.NewsInfo.summary', index=6,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['NewsInfo'] = _NEWSINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewsInfo = _reflection.GeneratedProtocolMessageType('NewsInfo', (_message.Message,), dict(
  DESCRIPTOR = _NEWSINFO,
  __module__ = 'tbclient.PbPage.NewsInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.PbPage.NewsInfo)
  ))
_sym_db.RegisterMessage(NewsInfo)


# @@protoc_insertion_point(module_scope)
