# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/PbPage/PostBanner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/PbPage/PostBanner.proto',
  package='tbclient.PbPage',
  syntax='proto2',
  serialized_pb=_b('\n tbclient/PbPage/PostBanner.proto\x12\x0ftbclient.PbPage\"\x8a\x01\n\nPostBanner\x12\x13\n\x0b\x62\x61nner_name\x18\x02 \x01(\t\x12\x12\n\nbanner_pic\x18\x01 \x01(\t\x12\x17\n\x0f\x62\x61nner_position\x18\x03 \x01(\r\x12\x12\n\nbanner_url\x18\x05 \x01(\t\x12\x13\n\x0b\x63lient_type\x18\x06 \x01(\r\x12\x11\n\tlink_type\x18\x04 \x01(\r')
)




_POSTBANNER = _descriptor.Descriptor(
  name='PostBanner',
  full_name='tbclient.PbPage.PostBanner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='banner_name', full_name='tbclient.PbPage.PostBanner.banner_name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banner_pic', full_name='tbclient.PbPage.PostBanner.banner_pic', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banner_position', full_name='tbclient.PbPage.PostBanner.banner_position', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banner_url', full_name='tbclient.PbPage.PostBanner.banner_url', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_type', full_name='tbclient.PbPage.PostBanner.client_type', index=4,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_type', full_name='tbclient.PbPage.PostBanner.link_type', index=5,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['PostBanner'] = _POSTBANNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PostBanner = _reflection.GeneratedProtocolMessageType('PostBanner', (_message.Message,), dict(
  DESCRIPTOR = _POSTBANNER,
  __module__ = 'tbclient.PbPage.PostBanner_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.PbPage.PostBanner)
  ))
_sym_db.RegisterMessage(PostBanner)


# @@protoc_insertion_point(module_scope)
