# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/ThreadList/ThreadListReqIdl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient.ThreadList import DataReq_pb2 as tbclient_dot_ThreadList_dot_DataReq__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/ThreadList/ThreadListReqIdl.proto',
  package='tbclient.ThreadList',
  syntax='proto2',
  serialized_pb=_b('\n*tbclient/ThreadList/ThreadListReqIdl.proto\x12\x13tbclient.ThreadList\x1a!tbclient/ThreadList/DataReq.proto\">\n\x10ThreadListReqIdl\x12*\n\x04\x64\x61ta\x18\x01 \x02(\x0b\x32\x1c.tbclient.ThreadList.DataReq')
  ,
  dependencies=[tbclient_dot_ThreadList_dot_DataReq__pb2.DESCRIPTOR,])




_THREADLISTREQIDL = _descriptor.Descriptor(
  name='ThreadListReqIdl',
  full_name='tbclient.ThreadList.ThreadListReqIdl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tbclient.ThreadList.ThreadListReqIdl.data', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=164,
)

_THREADLISTREQIDL.fields_by_name['data'].message_type = tbclient_dot_ThreadList_dot_DataReq__pb2._DATAREQ
DESCRIPTOR.message_types_by_name['ThreadListReqIdl'] = _THREADLISTREQIDL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThreadListReqIdl = _reflection.GeneratedProtocolMessageType('ThreadListReqIdl', (_message.Message,), dict(
  DESCRIPTOR = _THREADLISTREQIDL,
  __module__ = 'tbclient.ThreadList.ThreadListReqIdl_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ThreadList.ThreadListReqIdl)
  ))
_sym_db.RegisterMessage(ThreadListReqIdl)


# @@protoc_insertion_point(module_scope)
