# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/Adkiller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient.FrsPage import AdkillerAd_pb2 as tbclient_dot_FrsPage_dot_AdkillerAd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/Adkiller.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/FrsPage/Adkiller.proto\x12\x10tbclient.FrsPage\x1a!tbclient/FrsPage/AdkillerAd.proto\"\x84\x01\n\x08\x41\x64killer\x12\x13\n\x0b\x61\x64_left_num\x18\x04 \x01(\r\x12-\n\x07\x61\x64_list\x18\x05 \x03(\x0b\x32\x1c.tbclient.FrsPage.AdkillerAd\x12\x10\n\x08hint_url\x18\x03 \x01(\t\x12\x0f\n\x07show_ad\x18\x02 \x01(\r\x12\x11\n\tshow_hint\x18\x01 \x01(\r')
  ,
  dependencies=[tbclient_dot_FrsPage_dot_AdkillerAd__pb2.DESCRIPTOR,])




_ADKILLER = _descriptor.Descriptor(
  name='Adkiller',
  full_name='tbclient.FrsPage.Adkiller',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_left_num', full_name='tbclient.FrsPage.Adkiller.ad_left_num', index=0,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad_list', full_name='tbclient.FrsPage.Adkiller.ad_list', index=1,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hint_url', full_name='tbclient.FrsPage.Adkiller.hint_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_ad', full_name='tbclient.FrsPage.Adkiller.show_ad', index=3,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_hint', full_name='tbclient.FrsPage.Adkiller.show_hint', index=4,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=221,
)

_ADKILLER.fields_by_name['ad_list'].message_type = tbclient_dot_FrsPage_dot_AdkillerAd__pb2._ADKILLERAD
DESCRIPTOR.message_types_by_name['Adkiller'] = _ADKILLER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Adkiller = _reflection.GeneratedProtocolMessageType('Adkiller', (_message.Message,), dict(
  DESCRIPTOR = _ADKILLER,
  __module__ = 'tbclient.FrsPage.Adkiller_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.Adkiller)
  ))
_sym_db.RegisterMessage(Adkiller)


# @@protoc_insertion_point(module_scope)
