# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/AgreeBanner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient import SimpleUser_pb2 as tbclient_dot_SimpleUser__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/AgreeBanner.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\"tbclient/FrsPage/AgreeBanner.proto\x12\x10tbclient.FrsPage\x1a\x19tbclient/SimpleUser.proto\"h\n\x0b\x41greeBanner\x12\x10\n\x08icon_url\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x01 \x01(\t\x12,\n\x0etop_agree_user\x18\x04 \x03(\x0b\x32\x14.tbclient.SimpleUser\x12\x0b\n\x03url\x18\x03 \x01(\t')
  ,
  dependencies=[tbclient_dot_SimpleUser__pb2.DESCRIPTOR,])




_AGREEBANNER = _descriptor.Descriptor(
  name='AgreeBanner',
  full_name='tbclient.FrsPage.AgreeBanner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='icon_url', full_name='tbclient.FrsPage.AgreeBanner.icon_url', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='tbclient.FrsPage.AgreeBanner.text', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_agree_user', full_name='tbclient.FrsPage.AgreeBanner.top_agree_user', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='tbclient.FrsPage.AgreeBanner.url', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=187,
)

_AGREEBANNER.fields_by_name['top_agree_user'].message_type = tbclient_dot_SimpleUser__pb2._SIMPLEUSER
DESCRIPTOR.message_types_by_name['AgreeBanner'] = _AGREEBANNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgreeBanner = _reflection.GeneratedProtocolMessageType('AgreeBanner', (_message.Message,), dict(
  DESCRIPTOR = _AGREEBANNER,
  __module__ = 'tbclient.FrsPage.AgreeBanner_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.AgreeBanner)
  ))
_sym_db.RegisterMessage(AgreeBanner)


# @@protoc_insertion_point(module_scope)
