# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/AnchorPower.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/AnchorPower.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\"tbclient/FrsPage/AnchorPower.proto\x12\x10tbclient.FrsPage\"\x8e\x01\n\x0b\x41nchorPower\x12\x16\n\x0e\x61nchor_message\x18\x02 \x01(\t\x12\x19\n\x11\x63\x61n_add_live_post\x18\x03 \x01(\x05\x12\x1d\n\x15\x63\x61n_add_live_post_msg\x18\x05 \x01(\t\x12\x19\n\x11\x63\x61n_del_live_post\x18\x04 \x01(\x05\x12\x12\n\nhave_power\x18\x01 \x01(\x05')
)




_ANCHORPOWER = _descriptor.Descriptor(
  name='AnchorPower',
  full_name='tbclient.FrsPage.AnchorPower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anchor_message', full_name='tbclient.FrsPage.AnchorPower.anchor_message', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_add_live_post', full_name='tbclient.FrsPage.AnchorPower.can_add_live_post', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_add_live_post_msg', full_name='tbclient.FrsPage.AnchorPower.can_add_live_post_msg', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_del_live_post', full_name='tbclient.FrsPage.AnchorPower.can_del_live_post', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='have_power', full_name='tbclient.FrsPage.AnchorPower.have_power', index=4,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['AnchorPower'] = _ANCHORPOWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnchorPower = _reflection.GeneratedProtocolMessageType('AnchorPower', (_message.Message,), dict(
  DESCRIPTOR = _ANCHORPOWER,
  __module__ = 'tbclient.FrsPage.AnchorPower_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.AnchorPower)
  ))
_sym_db.RegisterMessage(AnchorPower)


# @@protoc_insertion_point(module_scope)
