# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/ClientPlatform.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient.FrsPage import StarSchedule_pb2 as tbclient_dot_FrsPage_dot_StarSchedule__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/ClientPlatform.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n%tbclient/FrsPage/ClientPlatform.proto\x12\x10tbclient.FrsPage\x1a#tbclient/FrsPage/StarSchedule.proto\"]\n\x0e\x43lientPlatform\x12\x14\n\x0cschedule_cal\x18\x01 \x01(\t\x12\x35\n\rstar_schedule\x18\x02 \x01(\x0b\x32\x1e.tbclient.FrsPage.StarSchedule')
  ,
  dependencies=[tbclient_dot_FrsPage_dot_StarSchedule__pb2.DESCRIPTOR,])




_CLIENTPLATFORM = _descriptor.Descriptor(
  name='ClientPlatform',
  full_name='tbclient.FrsPage.ClientPlatform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schedule_cal', full_name='tbclient.FrsPage.ClientPlatform.schedule_cal', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='star_schedule', full_name='tbclient.FrsPage.ClientPlatform.star_schedule', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=189,
)

_CLIENTPLATFORM.fields_by_name['star_schedule'].message_type = tbclient_dot_FrsPage_dot_StarSchedule__pb2._STARSCHEDULE
DESCRIPTOR.message_types_by_name['ClientPlatform'] = _CLIENTPLATFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientPlatform = _reflection.GeneratedProtocolMessageType('ClientPlatform', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTPLATFORM,
  __module__ = 'tbclient.FrsPage.ClientPlatform_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.ClientPlatform)
  ))
_sym_db.RegisterMessage(ClientPlatform)


# @@protoc_insertion_point(module_scope)
