# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/CommonForum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/CommonForum.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\"tbclient/FrsPage/CommonForum.proto\x12\x10tbclient.FrsPage\"#\n\x0b\x43ommonForum\x12\x14\n\x0c\x63ommon_forum\x18\x01 \x01(\t')
)




_COMMONFORUM = _descriptor.Descriptor(
  name='CommonForum',
  full_name='tbclient.FrsPage.CommonForum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_forum', full_name='tbclient.FrsPage.CommonForum.common_forum', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['CommonForum'] = _COMMONFORUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonForum = _reflection.GeneratedProtocolMessageType('CommonForum', (_message.Message,), dict(
  DESCRIPTOR = _COMMONFORUM,
  __module__ = 'tbclient.FrsPage.CommonForum_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.CommonForum)
  ))
_sym_db.RegisterMessage(CommonForum)


# @@protoc_insertion_point(module_scope)
