# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/Good.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/Good.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1btbclient/FrsPage/Good.proto\x12\x10tbclient.FrsPage\"\x13\n\x04Good\x12\x0b\n\x03num\x18\x01 \x01(\x05')
)




_GOOD = _descriptor.Descriptor(
  name='Good',
  full_name='tbclient.FrsPage.Good',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='tbclient.FrsPage.Good.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Good'] = _GOOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Good = _reflection.GeneratedProtocolMessageType('Good', (_message.Message,), dict(
  DESCRIPTOR = _GOOD,
  __module__ = 'tbclient.FrsPage.Good_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.Good)
  ))
_sym_db.RegisterMessage(Good)


# @@protoc_insertion_point(module_scope)
