# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/Group.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/Group.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/FrsPage/Group.proto\x12\x10tbclient.FrsPage\":\n\x05Group\x12\x13\n\x0bgroup_count\x18\x02 \x01(\x05\x12\x1c\n\x14hide_recommend_group\x18\x01 \x01(\x05')
)




_GROUP = _descriptor.Descriptor(
  name='Group',
  full_name='tbclient.FrsPage.Group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_count', full_name='tbclient.FrsPage.Group.group_count', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hide_recommend_group', full_name='tbclient.FrsPage.Group.hide_recommend_group', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['Group'] = _GROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Group = _reflection.GeneratedProtocolMessageType('Group', (_message.Message,), dict(
  DESCRIPTOR = _GROUP,
  __module__ = 'tbclient.FrsPage.Group_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.Group)
  ))
_sym_db.RegisterMessage(Group)


# @@protoc_insertion_point(module_scope)
