# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/Identify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/Identify.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/FrsPage/Identify.proto\x12\x10tbclient.FrsPage\"+\n\x08Identify\x12\n\n\x02id\x18\x02 \x01(\t\x12\x13\n\x0bis_identify\x18\x01 \x01(\x05')
)




_IDENTIFY = _descriptor.Descriptor(
  name='Identify',
  full_name='tbclient.FrsPage.Identify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tbclient.FrsPage.Identify.id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_identify', full_name='tbclient.FrsPage.Identify.is_identify', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['Identify'] = _IDENTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identify = _reflection.GeneratedProtocolMessageType('Identify', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFY,
  __module__ = 'tbclient.FrsPage.Identify_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.Identify)
  ))
_sym_db.RegisterMessage(Identify)


# @@protoc_insertion_point(module_scope)
