# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/Music.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/Music.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1ctbclient/FrsPage/Music.proto\x12\x10tbclient.FrsPage\">\n\x05Music\x12\x0e\n\x06isopen\x18\x04 \x01(\x05\x12\x0b\n\x03num\x18\x02 \x01(\x05\x12\x0b\n\x03pic\x18\x01 \x01(\t\x12\x0b\n\x03sid\x18\x03 \x01(\x05')
)




_MUSIC = _descriptor.Descriptor(
  name='Music',
  full_name='tbclient.FrsPage.Music',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isopen', full_name='tbclient.FrsPage.Music.isopen', index=0,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='tbclient.FrsPage.Music.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pic', full_name='tbclient.FrsPage.Music.pic', index=2,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sid', full_name='tbclient.FrsPage.Music.sid', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['Music'] = _MUSIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Music = _reflection.GeneratedProtocolMessageType('Music', (_message.Message,), dict(
  DESCRIPTOR = _MUSIC,
  __module__ = 'tbclient.FrsPage.Music_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.Music)
  ))
_sym_db.RegisterMessage(Music)


# @@protoc_insertion_point(module_scope)
