# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/PostPrefix.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/PostPrefix.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n!tbclient/FrsPage/PostPrefix.proto\x12\x10tbclient.FrsPage\"D\n\nPostPrefix\x12\x0c\n\x04mode\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t')
)




_POSTPREFIX = _descriptor.Descriptor(
  name='PostPrefix',
  full_name='tbclient.FrsPage.PostPrefix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='tbclient.FrsPage.PostPrefix.mode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='tbclient.FrsPage.PostPrefix.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='tbclient.FrsPage.PostPrefix.time', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='tbclient.FrsPage.PostPrefix.type', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['PostPrefix'] = _POSTPREFIX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PostPrefix = _reflection.GeneratedProtocolMessageType('PostPrefix', (_message.Message,), dict(
  DESCRIPTOR = _POSTPREFIX,
  __module__ = 'tbclient.FrsPage.PostPrefix_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.PostPrefix)
  ))
_sym_db.RegisterMessage(PostPrefix)


# @@protoc_insertion_point(module_scope)
