# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/RankInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/RankInfo.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/FrsPage/RankInfo.proto\x12\x10tbclient.FrsPage\"Y\n\x08RankInfo\x12\x10\n\x08\x64ir_rate\x18\x04 \x01(\x01\x12\x14\n\x0cmember_count\x18\x03 \x01(\x05\x12\x12\n\nsign_count\x18\x01 \x01(\x05\x12\x11\n\tsign_rank\x18\x02 \x01(\x05')
)




_RANKINFO = _descriptor.Descriptor(
  name='RankInfo',
  full_name='tbclient.FrsPage.RankInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir_rate', full_name='tbclient.FrsPage.RankInfo.dir_rate', index=0,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='member_count', full_name='tbclient.FrsPage.RankInfo.member_count', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign_count', full_name='tbclient.FrsPage.RankInfo.sign_count', index=2,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign_rank', full_name='tbclient.FrsPage.RankInfo.sign_rank', index=3,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['RankInfo'] = _RANKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RankInfo = _reflection.GeneratedProtocolMessageType('RankInfo', (_message.Message,), dict(
  DESCRIPTOR = _RANKINFO,
  __module__ = 'tbclient.FrsPage.RankInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.RankInfo)
  ))
_sym_db.RegisterMessage(RankInfo)


# @@protoc_insertion_point(module_scope)
