# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/RecmForumInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/RecmForumInfo.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n$tbclient/FrsPage/RecmForumInfo.proto\x12\x10tbclient.FrsPage\"m\n\rRecmForumInfo\x12\x0e\n\x06\x61vatar\x18\x05 \x01(\t\x12\x10\n\x08\x66orum_id\x18\x02 \x01(\x04\x12\x12\n\nforum_name\x18\x01 \x01(\t\x12\x14\n\x0cmember_count\x18\x03 \x01(\r\x12\x10\n\x08post_num\x18\x04 \x01(\r')
)




_RECMFORUMINFO = _descriptor.Descriptor(
  name='RecmForumInfo',
  full_name='tbclient.FrsPage.RecmForumInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='avatar', full_name='tbclient.FrsPage.RecmForumInfo.avatar', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forum_id', full_name='tbclient.FrsPage.RecmForumInfo.forum_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forum_name', full_name='tbclient.FrsPage.RecmForumInfo.forum_name', index=2,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='member_count', full_name='tbclient.FrsPage.RecmForumInfo.member_count', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_num', full_name='tbclient.FrsPage.RecmForumInfo.post_num', index=4,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['RecmForumInfo'] = _RECMFORUMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecmForumInfo = _reflection.GeneratedProtocolMessageType('RecmForumInfo', (_message.Message,), dict(
  DESCRIPTOR = _RECMFORUMINFO,
  __module__ = 'tbclient.FrsPage.RecmForumInfo_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.RecmForumInfo)
  ))
_sym_db.RegisterMessage(RecmForumInfo)


# @@protoc_insertion_point(module_scope)
