# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/SignForum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient.FrsPage import Forum_pb2 as tbclient_dot_FrsPage_dot_Forum__pb2
from tbclient.FrsPage import RankInfo_pb2 as tbclient_dot_FrsPage_dot_RankInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/SignForum.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n tbclient/FrsPage/SignForum.proto\x12\x10tbclient.FrsPage\x1a\x1ctbclient/FrsPage/Forum.proto\x1a\x1ftbclient/FrsPage/RankInfo.proto\"\xfb\x02\n\tSignForum\x12\x35\n\x11\x63urrent_rank_info\x18\x04 \x01(\x0b\x32\x1a.tbclient.FrsPage.RankInfo\x12\x10\n\x08\x66orum_id\x18\n \x01(\x03\x12+\n\nforum_info\x18\x03 \x01(\x0b\x32\x17.tbclient.FrsPage.Forum\x12\x11\n\tis_filter\x18\x02 \x01(\x05\x12\r\n\x05is_on\x18\x01 \x01(\x05\x12\x17\n\x0flevel1_dir_name\x18\x07 \x01(\t\x12\x17\n\x0flevel2_dir_name\x18\x08 \x01(\t\x12\x35\n\x11monthly_rank_info\x18\t \x01(\x0b\x32\x1a.tbclient.FrsPage.RankInfo\x12\x34\n\x10weekly_rank_info\x18\x06 \x01(\x0b\x32\x1a.tbclient.FrsPage.RankInfo\x12\x37\n\x13yesterday_rank_info\x18\x05 \x01(\x0b\x32\x1a.tbclient.FrsPage.RankInfo')
  ,
  dependencies=[tbclient_dot_FrsPage_dot_Forum__pb2.DESCRIPTOR,tbclient_dot_FrsPage_dot_RankInfo__pb2.DESCRIPTOR,])




_SIGNFORUM = _descriptor.Descriptor(
  name='SignForum',
  full_name='tbclient.FrsPage.SignForum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_rank_info', full_name='tbclient.FrsPage.SignForum.current_rank_info', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forum_id', full_name='tbclient.FrsPage.SignForum.forum_id', index=1,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forum_info', full_name='tbclient.FrsPage.SignForum.forum_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_filter', full_name='tbclient.FrsPage.SignForum.is_filter', index=3,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_on', full_name='tbclient.FrsPage.SignForum.is_on', index=4,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level1_dir_name', full_name='tbclient.FrsPage.SignForum.level1_dir_name', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level2_dir_name', full_name='tbclient.FrsPage.SignForum.level2_dir_name', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='monthly_rank_info', full_name='tbclient.FrsPage.SignForum.monthly_rank_info', index=7,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weekly_rank_info', full_name='tbclient.FrsPage.SignForum.weekly_rank_info', index=8,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yesterday_rank_info', full_name='tbclient.FrsPage.SignForum.yesterday_rank_info', index=9,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=497,
)

_SIGNFORUM.fields_by_name['current_rank_info'].message_type = tbclient_dot_FrsPage_dot_RankInfo__pb2._RANKINFO
_SIGNFORUM.fields_by_name['forum_info'].message_type = tbclient_dot_FrsPage_dot_Forum__pb2._FORUM
_SIGNFORUM.fields_by_name['monthly_rank_info'].message_type = tbclient_dot_FrsPage_dot_RankInfo__pb2._RANKINFO
_SIGNFORUM.fields_by_name['weekly_rank_info'].message_type = tbclient_dot_FrsPage_dot_RankInfo__pb2._RANKINFO
_SIGNFORUM.fields_by_name['yesterday_rank_info'].message_type = tbclient_dot_FrsPage_dot_RankInfo__pb2._RANKINFO
DESCRIPTOR.message_types_by_name['SignForum'] = _SIGNFORUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignForum = _reflection.GeneratedProtocolMessageType('SignForum', (_message.Message,), dict(
  DESCRIPTOR = _SIGNFORUM,
  __module__ = 'tbclient.FrsPage.SignForum_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.SignForum)
  ))
_sym_db.RegisterMessage(SignForum)


# @@protoc_insertion_point(module_scope)
