# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/WorldCupNews.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/WorldCupNews.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n#tbclient/FrsPage/WorldCupNews.proto\x12\x10tbclient.FrsPage\"*\n\x0cWorldCupNews\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t')
)




_WORLDCUPNEWS = _descriptor.Descriptor(
  name='WorldCupNews',
  full_name='tbclient.FrsPage.WorldCupNews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.FrsPage.WorldCupNews.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='tbclient.FrsPage.WorldCupNews.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['WorldCupNews'] = _WORLDCUPNEWS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorldCupNews = _reflection.GeneratedProtocolMessageType('WorldCupNews', (_message.Message,), dict(
  DESCRIPTOR = _WORLDCUPNEWS,
  __module__ = 'tbclient.FrsPage.WorldCupNews_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.WorldCupNews)
  ))
_sym_db.RegisterMessage(WorldCupNews)


# @@protoc_insertion_point(module_scope)
