# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbclient/FrsPage/WorldCup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbclient.FrsPage import WorldCupGame_pb2 as tbclient_dot_FrsPage_dot_WorldCupGame__pb2
from tbclient.FrsPage import WorldCupLottery_pb2 as tbclient_dot_FrsPage_dot_WorldCupLottery__pb2
from tbclient.FrsPage import WorldCupNews_pb2 as tbclient_dot_FrsPage_dot_WorldCupNews__pb2
from tbclient.FrsPage import WorldCupPk_pb2 as tbclient_dot_FrsPage_dot_WorldCupPk__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbclient/FrsPage/WorldCup.proto',
  package='tbclient.FrsPage',
  syntax='proto2',
  serialized_pb=_b('\n\x1ftbclient/FrsPage/WorldCup.proto\x12\x10tbclient.FrsPage\x1a#tbclient/FrsPage/WorldCupGame.proto\x1a&tbclient/FrsPage/WorldCupLottery.proto\x1a#tbclient/FrsPage/WorldCupNews.proto\x1a!tbclient/FrsPage/WorldCupPk.proto\"\xc4\x01\n\x08WorldCup\x12,\n\x04game\x18\x04 \x01(\x0b\x32\x1e.tbclient.FrsPage.WorldCupGame\x12\x32\n\x07lottery\x18\x03 \x01(\x0b\x32!.tbclient.FrsPage.WorldCupLottery\x12,\n\x04news\x18\x01 \x01(\x0b\x32\x1e.tbclient.FrsPage.WorldCupNews\x12(\n\x02pk\x18\x02 \x01(\x0b\x32\x1c.tbclient.FrsPage.WorldCupPk')
  ,
  dependencies=[tbclient_dot_FrsPage_dot_WorldCupGame__pb2.DESCRIPTOR,tbclient_dot_FrsPage_dot_WorldCupLottery__pb2.DESCRIPTOR,tbclient_dot_FrsPage_dot_WorldCupNews__pb2.DESCRIPTOR,tbclient_dot_FrsPage_dot_WorldCupPk__pb2.DESCRIPTOR,])




_WORLDCUP = _descriptor.Descriptor(
  name='WorldCup',
  full_name='tbclient.FrsPage.WorldCup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='tbclient.FrsPage.WorldCup.game', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lottery', full_name='tbclient.FrsPage.WorldCup.lottery', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='news', full_name='tbclient.FrsPage.WorldCup.news', index=2,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pk', full_name='tbclient.FrsPage.WorldCup.pk', index=3,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=399,
)

_WORLDCUP.fields_by_name['game'].message_type = tbclient_dot_FrsPage_dot_WorldCupGame__pb2._WORLDCUPGAME
_WORLDCUP.fields_by_name['lottery'].message_type = tbclient_dot_FrsPage_dot_WorldCupLottery__pb2._WORLDCUPLOTTERY
_WORLDCUP.fields_by_name['news'].message_type = tbclient_dot_FrsPage_dot_WorldCupNews__pb2._WORLDCUPNEWS
_WORLDCUP.fields_by_name['pk'].message_type = tbclient_dot_FrsPage_dot_WorldCupPk__pb2._WORLDCUPPK
DESCRIPTOR.message_types_by_name['WorldCup'] = _WORLDCUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorldCup = _reflection.GeneratedProtocolMessageType('WorldCup', (_message.Message,), dict(
  DESCRIPTOR = _WORLDCUP,
  __module__ = 'tbclient.FrsPage.WorldCup_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.FrsPage.WorldCup)
  ))
_sym_db.RegisterMessage(WorldCup)


# @@protoc_insertion_point(module_scope)
